// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxTVdOOLITgLIQH9x48xRBWuGATaRyPfw',
    appId: '1:632819139475:web:1f5116f3e65d028577de66',
    messagingSenderId: '632819139475',
    projectId: 'cits-assignment',
    authDomain: 'cits-assignment.firebaseapp.com',
    storageBucket: 'cits-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_77HBQiEq9F5Xx4w-guvCS3IAwHkFaOQ',
    appId: '1:632819139475:android:9a8e82fffa8c64dc77de66',
    messagingSenderId: '632819139475',
    projectId: 'cits-assignment',
    storageBucket: 'cits-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6C6aA5a-v2yYV7m4g7z_FlJMb-6yp7CY',
    appId: '1:632819139475:ios:9fa588133f60991577de66',
    messagingSenderId: '632819139475',
    projectId: 'cits-assignment',
    storageBucket: 'cits-assignment.appspot.com',
    iosClientId: '632819139475-13uo2bspntlla79c4p5a0e6a2suul5t7.apps.googleusercontent.com',
    iosBundleId: 'com.example.citsAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6C6aA5a-v2yYV7m4g7z_FlJMb-6yp7CY',
    appId: '1:632819139475:ios:9fa588133f60991577de66',
    messagingSenderId: '632819139475',
    projectId: 'cits-assignment',
    storageBucket: 'cits-assignment.appspot.com',
    iosClientId: '632819139475-13uo2bspntlla79c4p5a0e6a2suul5t7.apps.googleusercontent.com',
    iosBundleId: 'com.example.citsAssignment',
  );
}
